deployer: "0xc1937197F577F46462083c8271a70051E22a7810"
rpcEnvVar: "BASE_SEPOLIA_RPC_URL"
explorerUrl: "https://api-sepolia.basescan.org/api"
explorerApiKeyEnvVar: "BASESCAN_API_KEY"
totemsContract: "0x79fb5434201d70c5729abfec733b2da685010a22"
marketContract: "0x4ee91ab6a296954d6f71c93c5397bd5c3bde9054"
referrer: "0xc1937197F577F46462083c8271a70051E22a7810"
referrerFee: "0.0001 ether"
publish:
  - "Miner"
  - "Wrapper"
  - "Freezer"
  - "Blocklist"
  - "KYC"
  - "Extinguisher"
  - "ScamDefender"
  - "TransferControls"
  - "Allowlist"
  - "WhaleBlock"
  - "InnerCircle"
